**This part id for importing the libraries that i need for this project**

In [1]:
import pandas as pd

**Here is the name of the fils that included in Dataset.**

In [2]:
files = [
    "CAvideos.csv",
    "DEvideos.csv",
    "FRvideos.csv",
    "GBvideos.csv",
    "INvideos.csv",
    "JPvideos.csv",
    "KRvideos.csv",
    "MXvideos.csv",
    "RUvideos.csv",
    "USvideos.csv"
]

**1. Create a single dataframe with the concatenation of all input csv files, adding a column called country**

In [3]:
overall = []

In [9]:
for file in files:
    
    df_temp = pd.read_csv("../data/" + file, encoding="utf-8",encoding_errors="replace")
    
    country = file[:2]
    
    df_temp["country"] = country
    
    overall.append(df_temp)
    
    
df = pd.concat(overall, ignore_index= True)

In [10]:
df.columns

Index(['video_id', 'trending_date', 'title', 'channel_title', 'category_id',
       'publish_time', 'tags', 'views', 'likes', 'dislikes', 'comment_count',
       'thumbnail_link', 'comments_disabled', 'ratings_disabled',
       'video_error_or_removed', 'description', 'country'],
      dtype='object')

In [11]:
df["country"].unique()

array(['CA', 'DE', 'FR', 'GB', 'IN', 'JP', 'KR', 'MX', 'RU', 'US'],
      dtype=object)

**2. Extract all videos that have no tag.**

In [12]:
df["tags"].isna().sum()

np.int64(0)

In [13]:
df[df["tags"]== "[none]"].head(10)

,video_id,trending_date,title,channel_title,category_id,publish_time,tags,views,likes,dislikes,comment_count,thumbnail_link,comments_disabled,ratings_disabled,video_error_or_removed,description,country
41,JwboxqDylgg,17.14.11,Canada Soccer's Women's National Team v USA In...,Canada Soccer,17,2017-11-13T05:53:49.000Z,[none],36311,277,28,13,https://i.ytimg.com/vi/JwboxqDylgg/default.jpg,False,False,False,Canada Soccer's Women's National Team face riv...,CA
58,9B-q8h31Bpk,17.14.11,John Oliver Tackles Louis C.K. And Donald Trum...,TV Shows,22,2017-11-13T04:49:26.000Z,[none],106029,1270,101,181,https://i.ytimg.com/vi/9B-q8h31Bpk/default.jpg,False,False,False,"John Oliver on News, Politics ...",CA
78,1UE5Dq1rvUA,17.14.11,Taylor Swift Perform Ready For It - SNL,Ken Reactz,24,2017-11-12T05:18:02.000Z,[none],320964,8069,285,717,https://i.ytimg.com/vi/1UE5Dq1rvUA/default.jpg,False,False,False,Thanks for watching please subscribe and subsc...,CA
86,pmJQ4KwliX4,17.14.11,"LATEST Q POSTS: ROTHSCHILDS, HOUSE OF SAUD, lL...",James Munder,2,2017-11-12T21:25:40.000Z,[none],116820,1503,139,1066,https://i.ytimg.com/vi/pmJQ4KwliX4/default.jpg,False,False,False,https://pastebin.ca/3930472\n\nSupport My Chan...,CA
98,lHcXhBojpeQ,17.14.11,三屆TVB視帝，拋棄10年青梅竹馬髮妻，為娶小三還不惜與母絕交！,明星百曉生,22,2017-11-12T12:49:50.000Z,[none],88061,47,58,17,https://i.ytimg.com/vi/lHcXhBojpeQ/default.jpg,False,False,False,NaN,CA
99,Yo84eqYwP98,17.14.11,"LA PIRE PARTIE ft Le Rire Jaune, Pierre Croce,...",Le Labo,24,2017-11-12T15:00:02.000Z,[none],432721,14053,576,1161,https://i.ytimg.com/vi/Yo84eqYwP98/default.jpg,False,False,False,Le jeu de société: https://goo.gl/hhG1Ta\n\nGa...,CA
115,_QHEPUKBn9g,17.14.11,‘Too Alabama for Alabama’: SNL brutally mocks ...,MAXI POWER,23,2017-11-12T05:01:18.000Z,[none],20163,44,34,8,https://i.ytimg.com/vi/_QHEPUKBn9g/default.jpg,False,False,False,NaN,CA
120,SSLxfJ9rWeA,17.14.11,睡過范冰冰的20個男人首次揭秘，看完驚呆了！,nEWS 24-7,22,2017-11-12T11:31:55.000Z,[none],78178,65,64,24,https://i.ytimg.com/vi/SSLxfJ9rWeA/default.jpg,False,False,False,電視劇《亂世浮萍》即是其所投資。是包養范冰冰的第一位圈中人物。除了投資拍劇與廣告，更每月50...,CA
123,1YhtkrC2t0c,17.14.11,New Eritrean film Dama (ዳማ) part 13 Shalom En...,Shalom Entertainment,22,2017-11-11T17:21:54.000Z,[none],260199,4833,302,860,https://i.ytimg.com/vi/1YhtkrC2t0c/default.jpg,False,False,False,ሰላም ነዚ ቪድዮ ካብዚ ዳዉሎድ ምግባር ን ኣርቲስ ብዙሕ ጉዳት ሲለ ዘለዎ...,CA
131,O-_52G3aKVU,17.14.11,Taylor Swift SNL Call It What You Want on Satu...,vSpirit2,10,2017-11-12T09:23:20.000Z,[none],62915,1007,21,55,https://i.ytimg.com/vi/O-_52G3aKVU/default.jpg,False,False,False,"On Saturday Night Live November 11, 2017, Tayl...",CA

**3. For each channel, determine the total number of views**

In [14]:
df.groupby('channel_title')['views'].sum()

channel_title
! 세상에 무슨일이                7885954
!!8時だよ面白ネタ大集合              100414
!BTS・TWICE まとめ              14620
!Los amorosos Virales¡      12138
!t Live                    480076
                           ...
５分でできる DIY                 545214
ＢＡＳＨｔｖ                     232584
Ｋのフィッシングちゃんねる               74330
ＷＡＪＯＩＫＡ                    848258
💜Sandrea                   694310
Name: views, Length: 37824, dtype: int64

**4. Save all rows with disabled comments and disabled ratings, or that have video_error_or_removed in a new dataframe called excluded, and remove those rows from the original dataframe.**

In [15]:
excluded = df[((df['comments_disabled'] == True) & (df['ratings_disabled'] == True)) | (df['video_error_or_removed'] == True)]

In [16]:
excluded.count()

video_id                  5240
trending_date             5240
title                     5240
channel_title             5240
category_id               5240
publish_time              5240
tags                      5240
views                     5240
likes                     5240
dislikes                  5240
comment_count             5240
thumbnail_link            5240
comments_disabled         5240
ratings_disabled          5240
video_error_or_removed    5240
description               4614
country                   5240
dtype: int64

In [17]:
df = df.drop(excluded.index)

In [18]:
df[((df['comments_disabled'] == True) & (df['ratings_disabled'] == True)) | (df['video_error_or_removed'] == True)]

Empty DataFrame
Columns: [video_id, trending_date, title, channel_title, category_id, publish_time, tags, views, likes, dislikes, comment_count, thumbnail_link, comments_disabled, ratings_disabled, video_error_or_removed, description, country]
Index: []

**5. Add a like_ratio column storing the ratio between the number of likes and of dislikes**

In [24]:
df["like_ratio"] = df['likes'] / df['dislikes'].replace(0,1)

**6. Cluster the publish time into 10-minute intervals (e.g. from 02:20 to 02:30)**

In [25]:
df["publish_time"].dtype

datetime64[ns, UTC]

In [26]:
df["publish_time"].dt.minute

0          0
1          0
2          5
3          1
4          4
          ..
751879     0
751880     0
751881    34
751882     0
751883     9
Name: publish_time, Length: 746644, dtype: int32

In [27]:
df["publish_time"] = pd.to_datetime(df["publish_time"])

In [28]:
df["cluster"] = (df["publish_time"].dt.minute + df["publish_time"].dt.hour * 60) // 10

In [29]:
df.head(15)

,video_id,trending_date,title,channel_title,category_id,publish_time,tags,views,likes,dislikes,comment_count,thumbnail_link,comments_disabled,ratings_disabled,video_error_or_removed,description,country,like_ratio,cluster
0,n1WpP7iowLc,17.14.11,Eminem - Walk On Water (Audio) ft. Beyoncé,EminemVEVO,10,2017-11-10 17:00:03+00:00,"Eminem|""Walk""|""On""|""Water""|""Aftermath/Shady/In...",17158579,787425,43420,125882,https://i.ytimg.com/vi/n1WpP7iowLc/default.jpg,False,False,False,Eminem's new track Walk on Water ft. Beyoncé i...,CA,18.135076,102
1,0dBIkQ4Mz1M,17.14.11,PLUSH - Bad Unboxing Fan Mail,iDubbbzTV,23,2017-11-13 17:00:00+00:00,"plush|""bad unboxing""|""unboxing""|""fan mail""|""id...",1014651,127794,1688,13030,https://i.ytimg.com/vi/0dBIkQ4Mz1M/default.jpg,False,False,False,STill got a lot of packages. Probably will las...,CA,75.707346,102
2,5qpjK5DgCt4,17.14.11,"Racist Superman | Rudy Mancuso, King Bach & Le...",Rudy Mancuso,23,2017-11-12 19:05:24+00:00,"racist superman|""rudy""|""mancuso""|""king""|""bach""...",3191434,146035,5339,8181,https://i.ytimg.com/vi/5qpjK5DgCt4/default.jpg,False,False,False,WATCH MY PREVIOUS VIDEO ▶ \n\nSUBSCRIBE ► http...,CA,27.352500,114
3,d380meD0W0M,17.14.11,I Dare You: GOING BALD!?,nigahiga,24,2017-11-12 18:01:41+00:00,"ryan|""higa""|""higatv""|""nigahiga""|""i dare you""|""...",2095828,132239,1989,17518,https://i.ytimg.com/vi/d380meD0W0M/default.jpg,False,False,False,I know it's been a while since we did this sho...,CA,66.485168,108
4,2Vv-BfVoq4g,17.14.11,Ed Sheeran - Perfect (Official Music Video),Ed Sheeran,10,2017-11-09 11:04:14+00:00,"edsheeran|""ed sheeran""|""acoustic""|""live""|""cove...",33523622,1634130,21082,85067,https://i.ytimg.com/vi/2Vv-BfVoq4g/default.jpg,False,False,False,🎧: https://ad.gt/yt-perfect\n💰: https://atlant...,CA,77.513044,66
5,0yIWz1XEeyc,17.14.11,Jake Paul Says Alissa Violet CHEATED with LOGA...,DramaAlert,25,2017-11-13 07:37:51+00:00,"#DramaAlert|""Drama""|""Alert""|""DramaAlert""|""keem...",1309699,103755,4613,12143,https://i.ytimg.com/vi/0yIWz1XEeyc/default.jpg,False,False,False,► Follow for News! - https://twitter.com/KEEMS...,CA,22.491871,45
6,_uM5kFfkhB8,17.14.11,Vanoss Superhero School - New Students,VanossGaming,23,2017-11-12 23:52:13+00:00,"Funny Moments|""Montage video games""|""gaming""|""...",2987945,187464,9850,26629,https://i.ytimg.com/vi/_uM5kFfkhB8/default.jpg,False,False,False,Vanoss Merch Shop: https://vanoss.3blackdot.co...,CA,19.031878,143
7,2kyS6SvSYSE,17.14.11,WE WANT TO TALK ABOUT OUR MARRIAGE,CaseyNeistat,22,2017-11-13 17:13:01+00:00,SHANtell martin,748374,57534,2967,15959,https://i.ytimg.com/vi/2kyS6SvSYSE/default.jpg,False,False,False,SHANTELL'S CHANNEL - https://www.youtube.com/s...,CA,19.391304,103
8,JzCsM1vtn78,17.14.11,THE LOGANG MADE HISTORY. LOL. AGAIN.,Logan Paul Vlogs,24,2017-11-12 20:19:24+00:00,"logan paul vlog|""logan paul""|""logan""|""paul""|""o...",4477587,292837,4123,36391,https://i.ytimg.com/vi/JzCsM1vtn78/default.jpg,False,False,False,Join the movement. Be a Maverick ► https://Sho...,CA,71.025224,121
9,43sm-QwLcx4,17.14.11,Finally Sheldon is winning an argument about t...,Sheikh Musa,22,2017-11-10 14:10:46+00:00,"God|""Sheldon Cooper""|""Young Sheldon""",505161,4135,976,1484,https://i.ytimg.com/vi/43sm-QwLcx4/default.jpg,False,False,False,Sheldon is roasting pastor of the church\nyoun...,CA,4.236680,85
10,H1KBHFXm2Bg,17.14.11,21 Savage - Bank Account (Official Music Video),21 Savage,10,2017-11-10 19:00:02+00:00,"21 savage|""bank account""|""21 savage bank accou...",5068229,263596,8585,28976,https://i.ytimg.com/vi/H1KBHFXm2Bg/default.jpg,False,False,False,Watch the official music video of Bank Account...,CA,30.704252,114
11,U3xLOo-CNwo,17.14.11,12 Weird Ways To Sneak Food Into Class / Back ...,Troom Troom,26,2017-11-12 15:00:05+00:00,"sneak food|""how to sneak food into class""|""cla...",3153224,28451,2285,3312,https://i.ytimg.com/vi/U3xLOo-CNwo/default.jpg,False,False,False,Subscribe Here: http://bit.ly/2uaz0on\n12 Hot ...,CA,12.451204,90
12,FyZMnhUtLfE,17.14.11,猎场 | Game Of Hunting 12【TV版】（胡歌、張嘉譯、祖峰等主演）,大劇獨播,1,2017-11-12 16:00:01+00:00,"電視劇|""大陸電視劇""|""猎场""|""职场""|""商战""|""爱情""|""都市""|""胡歌""|""陈龙""...",158815,218,30,186,https://i.ytimg.com/vi/FyZMnhUtLfE/default.jpg,False,False,False,Thanks for watching the drama! Help more peopl...,CA,7.266667,96
13,7MxiQ4v0EnE,17.14.11,Daang ( Full Video ) | Mankirt Aulakh | Sukh S...,Speed Records,10,2017-11-11 16:41:15+00:00,"punjabi songs|""punjabi bhangra""|""punjabi music...",5718766,127477,7134,8063,https://i.ytimg.com/vi/7MxiQ4v0EnE/default.jpg,False,False,False,Song - Daang\nSinger - Mankirt Aulakh\nFaceboo...,CA,17.868937,100
14,LUzsOyWp9lw,17.14.11,YOUTUBERS REACT TO TOP 10 TWITTER ACCOUNTS OF ...,FBE,24,2017-11-12 22:00:01+00:00,"twitter|""top 10""|""Taylor Swift""|""YOUTUBERS REA...",960747,31810,668,5335,https://i.ytimg.com/vi/LUzsOyWp9lw/default.jpg,False,False,False,CLICK TO SUBSCRIBE TO THE YOUTUBERS IN THIS EP...,CA,47.619760,132

**7. For each interval, determine the number of videos, average number of likes and of dislikes.**

In [30]:
df.groupby("cluster").count()

,video_id,trending_date,title,channel_title,category_id,publish_time,tags,views,likes,dislikes,comment_count,thumbnail_link,comments_disabled,ratings_disabled,video_error_or_removed,description,country,like_ratio
cluster,,,,,,,,,,,,,,,,,,
0,5794,5794,5794,5794,5794,5794,5794,5794,5794,5794,5794,5794,5794,5794,5794,5490,5794,5794
1,3018,3018,3018,3018,3018,3018,3018,3018,3018,3018,3018,3018,3018,3018,3018,2824,3018,3018
2,2482,2482,2482,2482,2482,2482,2482,2482,2482,2482,2482,2482,2482,2482,2482,2282,2482,2482
3,3228,3228,3228,3228,3228,3228,3228,3228,3228,3228,3228,3228,3228,3228,3228,3014,3228,3228
4,2538,2538,2538,2538,2538,2538,2538,2538,2538,2538,2538,2538,2538,2538,2538,2316,2538,2538
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
139,3108,3108,3108,3108,3108,3108,3108,3108,3108,3108,3108,3108,3108,3108,3108,2896,3108,3108
140,2876,2876,2876,2876,2876,2876,2876,2876,2876,2876,2876,2876,2876,2876,2876,2576,2876,2876
141,3332,3332,3332,3332,3332,3332,3332,3332,3332,3332,3332,3332,3332,3332,3332,3132,3332,3332
142,2932,2932,2932,2932,2932,2932,2932,2932,2932,2932,2932,2932,2932,2932,2932,2680,2932,2932
143,2538,2538,2538,2538,2538,2538,2538,2538,2538,2538,2538,2538,2538,2538,2538,2294,2538,2538

In [31]:
df.groupby("cluster")[["video_id", "dislikes", "likes"]].agg(
    {"video_id": "count", "likes": "mean", "dislikes": "mean"}
)

         video_id         likes     dislikes
cluster
0            5794  61288.115637  3808.149465
1            3018  22748.138502  1449.836315
2            2482  21378.280419  1072.344883
3            3228  36853.560719   955.890954
4            2538  42198.623325  1909.301812
...           ...           ...          ...
139          3108  22783.840412  1110.168597
140          2876  30696.510431  1177.020862
141          3332  18159.173469   874.184874
142          2932  45736.581855  9341.549795
143          2538  10853.743893   505.701340

[144 rows x 3 columns]

**8. For each tag, determine the number of videos**

we consider 'none' as a tag and dont excluded from dataset

df_exploded = df_exploded[df_exploded["tag_list"] != "[none]"]

In [32]:
df["tags"].head(20)

0     Eminem|"Walk"|"On"|"Water"|"Aftermath/Shady/In...
1     plush|"bad unboxing"|"unboxing"|"fan mail"|"id...
2     racist superman|"rudy"|"mancuso"|"king"|"bach"...
3     ryan|"higa"|"higatv"|"nigahiga"|"i dare you"|"...
4     edsheeran|"ed sheeran"|"acoustic"|"live"|"cove...
5     #DramaAlert|"Drama"|"Alert"|"DramaAlert"|"keem...
6     Funny Moments|"Montage video games"|"gaming"|"...
7                                       SHANtell martin
8     logan paul vlog|"logan paul"|"logan"|"paul"|"o...
9                  God|"Sheldon Cooper"|"Young Sheldon"
10    21 savage|"bank account"|"21 savage bank accou...
11    sneak food|"how to sneak food into class"|"cla...
12    電視劇|"大陸電視劇"|"猎场"|"职场"|"商战"|"爱情"|"都市"|"胡歌"|"陈龙"...
13    punjabi songs|"punjabi bhangra"|"punjabi music...
14    twitter|"top 10"|"Taylor Swift"|"YOUTUBERS REA...
15    buzzfeed|"buzzfeedblue"|"outsmarted"|"outsmart...
16        prank|"pranks"|"nelk"|"nelkfilmz"|"nelkfilms"
17    Graham Norton|"Graham Norton Show Official"|"E...
18    Rooster Teeth|"RT"|"animation"|"television"|"f...
19    sharry mann|"sharry mann new song"|"sharry man...
Name: tags, dtype: object

In [33]:
df["tag_list"] = df["tags"].str.split("|")

In [34]:
df_exploded = df.explode("tag_list")  #turns each element of list into row

In [35]:
df_exploded["tag_list"].value_counts()

tag_list
[none]                              74418
"funny"                             29866
"comedy"                            23924
"2018"                              22058
"news"                              11910
                                    ...
"chabos wissen wer der babo ist"        2
"#невыборы2018"                         2
"Senora"                                2
Sampdoria                               2
"langford"                              2
Name: count, Length: 886936, dtype: int64

**9. Find the tags with the largest number of videos**

In [36]:
tags_count = df_exploded["tag_list"].value_counts()

In [37]:
tags_count.idxmax()

'[none]'

If we want to dont consider none as a tag so the largest number is:

In [38]:
tag_count_r = tags_count.drop("[none]")

In [39]:
tag_count_r.idxmax()

'"funny"'

**10. For each (tag, country) pair, compute average ratio likes/dislikes**

In [40]:
df_exploded["average_ratio"] = df["likes"] / df["dislikes"]

In [41]:
df_exploded.groupby(["tag_list", "country"])["average_ratio"].mean().reset_index()

,tag_list,country,average_ratio
0,,CA,8.618739
1,,DE,24.344225
2,,FR,16.424636
3,,IN,7.659699
4,,JP,9.894877
...,...,...,...
1136793,ＴＨＥカラオケ★バトル,JP,7.450000
1136794,ｓ１３,JP,15.335714
1136795,🍊 Exatlón México 🍉 programa 🍒 88 EP4-👢 14/02/2...,MX,5.750000
1136796,🔥BROMA A FALCONY EL SUSTO DE SU VIDA🔥,MX,128.516035
1136797,🚀 smartpixel.com.ua,RU,0.714286

**11. For each (trending_date, country) pair, the video with the largest number of views**

In [42]:
idx = df.groupby(['trending_date', 'country'])['views'].idxmax()

In [43]:
df.loc[idx, ['trending_date', 'country', 'video_id', 'title', 'channel_title', 'views']].reset_index()

,index,trending_date,country,video_id,title,channel_title,views
0,3398,17.01.12,CA,6ZfuNTqbHE8,Marvel Studios' Avengers: Infinity War Officia...,Marvel Entertainment,56367282
1,44280,17.01.12,DE,6ZfuNTqbHE8,Marvel Studios' Avengers: Infinity War Officia...,Marvel Entertainment,56367282
2,85252,17.01.12,FR,3VbHg5fqBYw,Avengers: Infinity War Trailer Tease,Marvel Entertainment,7281189
3,126032,17.01.12,GB,TyHvyGVs42U,"Luis Fonsi, Demi Lovato - Échame La Culpa",LuisFonsiVEVO,143408235
4,164617,17.01.12,IN,6ZfuNTqbHE8,Marvel Studios' Avengers: Infinity War Officia...,Marvel Entertainment,56367282
...,...,...,...,...,...,...,...
1962,216792,18.31.05,JP,aJOTlE1K90k,Maroon 5 - Girls Like You ft. Cardi B,Maroon5VEVO,3057987
1963,251198,18.31.05,KR,ntWSnDV0MYs,[MV] AOA _ Bingle Bangle(빙글뱅글),1theK (원더케이),4150448
1964,291483,18.31.05,MX,xTlNMmZKwpA,"Cardi B, Bad Bunny & J Balvin - I Like It [Off...",Cardi B,20723565
1965,332058,18.31.05,RU,1nX0kF2UwDc,[BadComedian] - Движение Вверх (Плагиат или ве...,BadComedian,3125598
1966,373139,18.31.05,US,VYOjWnS4cMY,Childish Gambino - This Is America (Official V...,ChildishGambinoVEVO,217750076

**12. Divide trending_date into three columns: year, month, day**

In [44]:
df["trending_date"].dtype

dtype('O')

In [45]:
df["trending_date"]

0         17.14.11
1         17.14.11
2         17.14.11
3         17.14.11
4         17.14.11
            ...
751879    18.14.06
751880    18.14.06
751881    18.14.06
751882    18.14.06
751883    18.14.06
Name: trending_date, Length: 746644, dtype: object

In [46]:
df[['year', 'day', 'month']] = df['trending_date'].str.split('.', expand = True)

### This is done by string but there is way also for the converting into datetime

In [47]:
df["trending_date"] = pd.to_datetime(df["trending_date"], format="%y.%d.%m")

In [48]:
df["year"] = df["trending_date"].dt.year
df["month"] = df["trending_date"].dt.month
df["day"] = df["trending_date"].dt.day

**13. For each (month, country) pair, the video with the largest number of views**

In [50]:
idxx = df.groupby(['month', 'country'])['views'].idxmax()

In [51]:
df.loc[idxx, ['month', 'country', 'video_id', 'title', 'channel_title', 'views']].reset_index()

,index,month,country,video_id,title,channel_title,views
0,11214,1,CA,LsoLEjrDogU,Bruno Mars - Finesse (Remix) [Feat. Cardi B] [...,Bruno Mars,43067983
1,51930,1,DE,LsoLEjrDogU,Bruno Mars - Finesse (Remix) [Feat. Cardi B] [...,Bruno Mars,37728802
2,92853,1,FR,LsoLEjrDogU,Bruno Mars - Finesse (Remix) [Feat. Cardi B] [...,Bruno Mars,37728802
3,135208,1,GB,LsoLEjrDogU,Bruno Mars - Finesse (Remix) [Feat. Cardi B] [...,Bruno Mars,90598955
4,173405,1,IN,dfnCAmr569k,"Taylor Swift - End Game ft. Ed Sheeran, Future",TaylorSwiftVEVO,42019590
...,...,...,...,...,...,...,...
72,166769,12,IN,FlsCjmMhFmw,YouTube Rewind: The Shape of 2017 | #YouTubeRe...,YouTube Spotlight,125432237
73,224092,12,KR,FlsCjmMhFmw,YouTube Rewind: The Shape of 2017 | #YouTubeRe...,YouTube Spotlight,113876217
74,259064,12,MX,FlsCjmMhFmw,YouTube Rewind: The Shape of 2017 | #YouTubeRe...,YouTube Spotlight,100912384
75,299087,12,RU,FlsCjmMhFmw,YouTube Rewind: The Shape of 2017 | #YouTubeRe...,YouTube Spotlight,52611730
76,341174,12,US,FlsCjmMhFmw,YouTube Rewind: The Shape of 2017 | #YouTubeRe...,YouTube Spotlight,149376127

**14. Read all json files with the video categories**

In [104]:
import json

In [105]:
from pathlib import Path

In [106]:
import pandas as pd

In [107]:
categories_folder = Path("../catagories")

In [136]:
# 2) Collect the JSON files
json_files = sorted(categories_folder.glob("*_category_id.json"))
print("Found files:", [p.name for p in json_files])

Found files: ['CA_category_id.json', 'DE_category_id.json', 'FR_category_id.json', 'GB_category_id.json', 'IN_category_id.json', 'JP_category_id.json', 'KR_category_id.json', 'MX_category_id.json', 'RU_category_id.json', 'US_category_id.json']

In [137]:
json_files

[PosixPath('../catagories/CA_category_id.json'),
 PosixPath('../catagories/DE_category_id.json'),
 PosixPath('../catagories/FR_category_id.json'),
 PosixPath('../catagories/GB_category_id.json'),
 PosixPath('../catagories/IN_category_id.json'),
 PosixPath('../catagories/JP_category_id.json'),
 PosixPath('../catagories/KR_category_id.json'),
 PosixPath('../catagories/MX_category_id.json'),
 PosixPath('../catagories/RU_category_id.json'),
 PosixPath('../catagories/US_category_id.json')]

In [138]:
dfs = []

In [148]:
for jf in json_files:
    country = jf.stem.split("_")[0].upper()  # CA_category_id -> CA

    with open(jf, "r", encoding="utf-8") as f:
        data = json.load(f)

    items = data.get("items", [])
    if len(items) == 0:
        continue

    cat_df = pd.json_normalize(items)

    cat_df = cat_df[["id", "snippet.title", "snippet.assignable"]].rename(columns={
        "id": "category_id",
        "snippet.title": "category_name",
        "snippet.assignable": "assignable"
    })

    cat_df["category_id"] = cat_df["category_id"].astype(str)
    cat_df["country"] = country

    dfs.append(cat_df)

In [154]:
categories_df = pd.concat(dfs, ignore_index=True)
categories_df.head()

  category_id     category_name  assignable country
0           1  Film & Animation        True      CA
1           2  Autos & Vehicles        True      CA
2          10             Music        True      CA
3          15    Pets & Animals        True      CA
4          17            Sports        True      CA

In [158]:
categories_df['country'].unique()

array(['CA', 'DE', 'FR', 'GB', 'IN', 'JP', 'KR', 'MX', 'RU', 'US'],
      dtype=object)

**15. For each country, determine how many videos have a category that is not assignable.**

In [159]:
df["category_id"] = df["category_id"].astype(str)
categories_df["category_id"] = categories_df["category_id"].astype(str)

In [160]:
df_merged = df.merge(
    categories_df[["country", "category_id", "assignable"]],
    on=["country", "category_id"],
    how="left"
)

In [165]:
df_merged

,video_id,trending_date,title,channel_title,category_id,publish_time,tags,views,likes,dislikes,...,video_error_or_removed,description,country,like_ratio,cluster,tag_list,year,day,month,assignable
0,n1WpP7iowLc,2017-11-14,Eminem - Walk On Water (Audio) ft. Beyoncé,EminemVEVO,10,2017-11-10 17:00:03+00:00,"Eminem|""Walk""|""On""|""Water""|""Aftermath/Shady/In...",17158579,787425,43420,...,False,Eminem's new track Walk on Water ft. Beyoncé i...,CA,18.135076,102,"[Eminem, ""Walk"", ""On"", ""Water"", ""Aftermath/Sha...",2017,14,11,True
1,n1WpP7iowLc,2017-11-14,Eminem - Walk On Water (Audio) ft. Beyoncé,EminemVEVO,10,2017-11-10 17:00:03+00:00,"Eminem|""Walk""|""On""|""Water""|""Aftermath/Shady/In...",17158579,787425,43420,...,False,Eminem's new track Walk on Water ft. Beyoncé i...,CA,18.135076,102,"[Eminem, ""Walk"", ""On"", ""Water"", ""Aftermath/Sha...",2017,14,11,True
2,0dBIkQ4Mz1M,2017-11-14,PLUSH - Bad Unboxing Fan Mail,iDubbbzTV,23,2017-11-13 17:00:00+00:00,"plush|""bad unboxing""|""unboxing""|""fan mail""|""id...",1014651,127794,1688,...,False,STill got a lot of packages. Probably will las...,CA,75.707346,102,"[plush, ""bad unboxing"", ""unboxing"", ""fan mail""...",2017,14,11,True
3,0dBIkQ4Mz1M,2017-11-14,PLUSH - Bad Unboxing Fan Mail,iDubbbzTV,23,2017-11-13 17:00:00+00:00,"plush|""bad unboxing""|""unboxing""|""fan mail""|""id...",1014651,127794,1688,...,False,STill got a lot of packages. Probably will las...,CA,75.707346,102,"[plush, ""bad unboxing"", ""unboxing"", ""fan mail""...",2017,14,11,True
4,5qpjK5DgCt4,2017-11-14,"Racist Superman | Rudy Mancuso, King Bach & Le...",Rudy Mancuso,23,2017-11-12 19:05:24+00:00,"racist superman|""rudy""|""mancuso""|""king""|""bach""...",3191434,146035,5339,...,False,WATCH MY PREVIOUS VIDEO ▶ \n\nSUBSCRIBE ► http...,CA,27.352500,114,"[racist superman, ""rudy"", ""mancuso"", ""king"", ""...",2017,14,11,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1487915,D6Oy4LfoqsU,2018-06-14,I GAVE SAFIYA NYGAARD A PERFECT HAIR MAKEOVER ...,Brad Mondo,24,2018-05-18 17:34:22+00:00,I gave safiya nygaard a perfect hair makeover ...,1066451,48068,1032,...,False,I had so much fun transforming Safiyas hair in...,US,46.577519,105,[I gave safiya nygaard a perfect hair makeover...,2018,14,6,True
1487916,oV0zkMe1K8s,2018-06-14,How Black Panther Should Have Ended,How It Should Have Ended,1,2018-05-17 17:00:04+00:00,"Black Panther|""HISHE""|""Marvel""|""Infinity War""|...",5660813,192957,2846,...,False,How Black Panther Should Have EndedWatch More ...,US,67.799368,102,"[Black Panther, ""HISHE"", ""Marvel"", ""Infinity W...",2018,14,6,True
1487917,oV0zkMe1K8s,2018-06-14,How Black Panther Should Have Ended,How It Should Have Ended,1,2018-05-17 17:00:04+00:00,"Black Panther|""HISHE""|""Marvel""|""Infinity War""|...",5660813,192957,2846,...,False,How Black Panther Should Have EndedWatch More ...,US,67.799368,102,"[Black Panther, ""HISHE"", ""Marvel"", ""Infinity W...",2018,14,6,True
1487918,ooyjaVdt-jA,2018-06-14,Official Call of Duty®: Black Ops 4 — Multipla...,Call of Duty,20,2018-05-17 17:09:38+00:00,"call of duty|""cod""|""activision""|""Black Ops 4""",10306119,357079,212976,...,False,Call of Duty: Black Ops 4 Multiplayer raises t...,US,1.676616,102,"[call of duty, ""cod"", ""activision"", ""Black Ops...",2018,14,6,True
1487919,ooyjaVdt-jA,2018-06-14,Official Call of Duty®: Black Ops 4 — Multipla...,Call of Duty,20,2018-05-17 17:09:38+00:00,"call of duty|""cod""|""activision""|""Black Ops 4""",10306119,357079,212976,...,False,Call of Duty: Black Ops 4 Multiplayer raises t...,US,1.676616,102,"[call of duty, ""cod"", ""activision"", ""Black Ops...",2018,14,6,True

In [162]:
not_assignable_df = df_merged[df_merged["assignable"] == False]
not_assignable_df.shape

(4060, 24)

In [167]:
result = (
    not_assignable_df
    .groupby("country")
    .size()
    .reset_index(name="num_videos_not_assignable")
    .sort_values("num_videos_not_assignable", ascending=False)
)
result

  country  num_videos_not_assignable
4      IN                        884
7      RU                        780
5      KR                        668
0      CA                        520
2      FR                        448
1      DE                        440
8      US                        228
3      GB                         80
6      MX                         12

In [168]:
result_all = (
    df_merged.assign(not_assignable = df_merged["assignable"] == False)
    .groupby("country")["not_assignable"]
    .sum()
    .reset_index(name="num_videos_not_assignable")
    .sort_values("num_videos_not_assignable", ascending=False)
)

result_all

  country  num_videos_not_assignable
4      IN                        884
8      RU                        780
6      KR                        668
0      CA                        520
2      FR                        448
1      DE                        440
9      US                        228
3      GB                         80
7      MX                         12
5      JP                          0